assert(vim.o.clipboard == "unnamedplus")
assert(vim.o.termguicolors)
assert(vim.o.relativenumber)
assert(not vim.o.cursorline)
assert(vim.o.tabline == "")
assert(vim.o.pumborder == "single")
assert(vim.o.winborder == "single")
assert(not vim.tbl_contains(vim.split(vim.o.completeopt, ','), 'noselect'))
assert(vim.tbl_contains(vim.split(vim.o.completeopt, ','), 'noinsert'))
assert(vim.o.guicursor:find("n%-c:block"))
assert(vim.o.guicursor:find("i%-ci:ver25"))
assert(vim.o.guicursor:find("v%-ve%-r%-cr%-o:hor20"))
assert(vim.api.nvim_get_hl(0, { name = 'Pmenu', link = false }).bg == 0)
assert(vim.api.nvim_get_hl(0, { name = 'PmenuSel', link = false }).fg == 0xffffff)
assert(vim.api.nvim_get_hl(0, { name = 'PmenuSel', link = false }).bg == 0x3a3a3a)

local function with_buffer(name, options, lines, f)
	local bufnr = vim.api.nvim_create_buf(true, false)
	vim.api.nvim_buf_set_name(bufnr, name)
	vim.bo[bufnr].buftype = options.buftype or ""
	vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
	vim.bo[bufnr].modifiable = options.modifiable ~= false
	vim.bo[bufnr].readonly = options.readonly or false
	f(bufnr)
	vim.api.nvim_buf_delete(bufnr, { force = true })
end

local root = vim.fn.tempname()
with_buffer(root .. ".lua", {}, { "value  ", "clean" }, function(bufnr)
	assert(Config.should_trim_trailing_whitespace(bufnr))
	Config.trim_trailing_whitespace(bufnr)
	assert(vim.deep_equal(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false), { "value", "clean" }))
end)

with_buffer(root .. ".go", {}, { "// Code generated by test. DO NOT EDIT.", "value  " }, function(bufnr)
	assert(not Config.should_trim_trailing_whitespace(bufnr))
	Config.trim_trailing_whitespace(bufnr)
	assert(vim.api.nvim_buf_get_lines(bufnr, 1, 2, false)[1] == "value  ")
end)

with_buffer(root .. ".txt", { buftype = "nofile" }, { "value  " }, function(bufnr)
	assert(not Config.should_trim_trailing_whitespace(bufnr))
end)

with_buffer(root .. ".txt", { modifiable = false }, { "value  " }, function(bufnr)
	assert(not Config.should_trim_trailing_whitespace(bufnr))
end)

local write_path = root .. ".write"
vim.fn.writefile({ "value  " }, write_path)
local undofile = vim.o.undofile
vim.o.undofile = false
vim.cmd.edit(vim.fn.fnameescape(write_path))
vim.cmd.write()
assert(vim.fn.readfile(write_path)[1] == "value")
vim.cmd.bwipeout()
vim.o.undofile = undofile
vim.fn.delete(write_path)
