local config = table.concat(vim.fn.readfile('plugin/40_plugins.lua'), '\n')

assert(config:find("version = vim.version.range%('2%.%*'%)"))
assert(config:find("https://github.com/NeogitOrg/neogit"))
assert(config:find("require%('neogit'%).setup%(%)"))
assert(config:find("vim.keymap.set%('n', '<Leader>v', '<Cmd>Neogit<CR>'"))
assert(not config:find('neotest'))
assert(not config:find('plenary'))
assert(config:find("'<LocalLeader>tt'"))
assert(config:find("tags = %{ require%('overseer'%).TAG.TEST %}"))
assert(config:find("https://github.com/nvim%-lualine/lualine%.nvim"))
assert(config:find("lualine%.setup%(config%)"))
assert(config:find("ins_right%(%{ 'overseer' %}%)"))
assert(config:find("nvim_get_hl%(0, %{%s*name = group, link = false%s*%}%)"))
assert(config:find("bg = '#111111'"))
assert(config:find("vim.keymap.set%('n', '<A%-n>', '<Cmd>cnext<CR>'"))
assert(config:find("vim.keymap.set%('n', '<A%-p>', '<Cmd>cprevious<CR>'"))
assert(config:find("vim.keymap.set%('n', '<Leader>q', function%(%) require%('quicker'%).toggle%(%)"))
assert(config:find("vim.keymap.set%('n', '<Leader>%$%$', '<Cmd>OverseerRun<CR>'"))
assert(config:find("vim.api.nvim_create_user_command%('OverseerRestartLast'"))
assert(config:find("vim.cmd.cnoreabbrev%('OS OverseerShell'%)"))
assert(config:find("vim.keymap.set%('n', '<Leader>%$r', '<Cmd>OverseerRestartLast<CR>'"))
assert(config:find("vim.keymap.set%('n', '<Leader>%$s', ':OverseerShell '"))
assert(config:find("vim.keymap.set%('n', '<Leader>%$t', '<Cmd>OverseerToggle<CR>'"))
assert(not config:find('OverseerTaskAction'))
assert(config:find("https://github.com/julienvincent/nvim%-paredit"))
assert(config:find("require%('nvim%-paredit'%)%.setup%(%{"))
assert(config:find("filetypes = {%s*'lisp'%s*}"))
